/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    checkstyle
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("org.javamodularity.moduleplugin") version "2.0.0"
    id("org.beryx.jlink") version "4.0.0"
}

javafx {
    version = "25"
    modules("javafx.controls", "javafx.fxml")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation(libs.guava)
    implementation("org.eclipse.store:storage-embedded:4.0.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    modularity.inferModulePath = true
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainModule = "schengen.shortstay"
    // Define the main class for the application.
    mainClass = "schengen.shortstay.App"
    applicationDefaultJvmArgs = listOf("--add-exports", "java.base/jdk.internal.misc=org.eclipse.serializer.base")
    applicationDefaultJvmArgs += listOf("--enable-native-access=javafx.graphics")
}

jlink {
    addExtraModulePath("./app/jmods/openjfx-26.0.1_linux-x64_bin-jmods/javafx-jmods-26.0.1")
    addExtraDependencies("javafx")
    mergedModule {
        requires("javafx.fxml")
        requires("javafx.controls")
        requires("javafx.graphics")
    }
    options = listOf("--strip-java-debug-attributes", "--compress", "zip-6", "--no-header-files", "--no-man-pages")
    launcher {
        name = "shortStay"
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
