/*
 * This source file was generated by the Gradle 'init' task
 */
package schengen.shortstay;

import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        //schengen.shortstay.App classUnderTest = new schengen.shortstay.App();
        assert(true);
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
